name: Deploy to XServer

on:
  push:
    branches:
      - main  # メインブランチにプッシュされた時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # 環境を指定
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.XSERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 10022 -H ${{ secrets.XSERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -p 10022 ${{ secrets.XSERVER_USER }}@${{ secrets.XSERVER_HOST }} "echo 'SSH connected successfully!'"

